spring:
  application:
    name: User Service Consumer
  cloud:
    zookeeper:
      connectString: localhost:2181
#  cloud:
#    zookeeper:
#      dependencies:
#        User-Service-Producer:
#          required: true
#          version: 1.0.0
server:
  port: 8088

feign:
  compression:
    request:
      enable: true
    response:
      enable: true
#  hystrix:
#    enable: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
